pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
              sh "git clone https://github.com/horpehyehmii/testf.git"
            }
        }
        stage('Load and Run Groovy Script') {
            steps {
                script {

                  sh "pwd"
                   
                }
            }
        }
    }
}
